---
kind: pipeline
name: default
type: docker

steps:
- name: pytest
  image: python:3.6-alpine3.13
  commands:
    - apk add --no-cache g++ libffi-dev
    - wget -O- https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
    - /root/.local/bin/poetry install
    - /root/.local/bin/poetry run pytest

- name: docker
  image: plugins/docker
  settings:
    repo: yavook/kind
    auto_tag: true
#    tags:
#    - edge
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD