---
kind: pipeline
name: default

steps:
- name: pytest
  image: python:3.6-alpine3.13
  commands:
    - wget -O- https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
    - source $HOME/.poetry/env && poetry install
    - source $HOME/.poetry/env && poetry run pytest

- name: docker
  image: plugins/docker
  settings:
    repo: ldericher/kind
    auto_tag: true
#    tags:
#    - edge
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD