---
kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ldericher/kind
    # auto_tag: true
    tags:
    - latest
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD