---
kind: pipeline
name: default
type: docker

steps:
- name: pytest
  image: python:3.6-alpine3.13
  commands:
    - apk add --no-cache g++ libffi-dev curl
    - wget -O- https://install.python-poetry.org | python3 - --version 1.1.15
    - /root/.local/bin/poetry install
    - /root/.local/bin/poetry run pytest

- name: docker
  image: plugins/docker
  settings:
    repo: yavook/kind
    auto_tag: true
#    tags:
#    - edge
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD