version: "2"

networks:
  # reachable from outside
  default:
    driver: bridge
  # interconnects projects
  kiwi_hub:
    external:
      name: $KIWI_HUB_NAME

services:
  hello-world:
    image: alpine:latest
    command: sh -c 'LOOP=1; while :; do echo Hello World "$$LOOP"; LOOP=$$(($$LOOP + 1)); sleep 10; done'
  foo-bar:
    image: alpine:latest
    command: sh -c 'LOOP=1; while :; do echo Foo Bar "$$LOOP"; LOOP=$$(($$LOOP + 1)); sleep 20; done'
