version: "2"

networks:
  # reachable from outside
  default:
    driver: bridge
  # interconnects projects
  kiwihub:
    external:
      name: $KIWI_HUB_NAME

services:
  hello-world:
    image: alpine:latest
    command: sh -c 'while :; do echo Hello World "$$RANDOM"; sleep 10; done'
